.. toctree::
   :maxdepth: 2

   commands
   installation
   templating
   introduction
   overview
   faq
   ccsdata
   examples
   encryption
   man_pages/sdlc-gerrit-branching-and-workflow
   man_pages/sdlc-gerrit-release-tagging
   man_pages/ansible-introduction-and-primitives
   man_pages/ansible-site-variable-framework
   man_pages/sdlc-setup-process
   man_pages/ansible-playbook-runtime-commands
   man_pages/heighliner-workflow
   man_pages/puppet-introduction-and-primitives
